### ISSUE TITLE
CodeFocusHandler will not compile with VS 2015 nor 2019

### ISSUE THREAD

**Issue by PhilG57** [CoatiSoftware/Sourcetrail#985]
Receive error C2664 on lines 92, 97, and 104 of CodeFocusHandler when compiling with Visual Studio 2015 or 2019.

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void CodeFocusHandler::setCurrentFocus(const CodeFocusHandler::Focus &,bool)': cannot convert argument 1 from 'initializer list' to 'const CodeFocusHandler::Focus &'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	92	

void CodeFocusHandler::setFocusedLocationId(
	QtCodeArea* area, size_t lineNumber, size_t columnNumber, Id locationId, const std::vector<Id>& tokenIds, bool updateTargetColumn, bool fromMouse)
{
	if (updateTargetColumn)
	{
		m_targetColumn = columnNumber;
	}

	setCurrentFocus({nullptr, area, nullptr, lineNumber, columnNumber, locationId, tokenIds}, fromMouse);
	setCurrentFocus({}, fromMouse);
}

**Comment by egraether** [comment]
Are these the only errors you get?

**Comment by PhilG57** [comment]
The same error on three lines of code: 92, 97, and 104.  When I commented out those lines, and compiled with VS2015, I of course proceeded further into the build.  But eventually I ran into an "rc.exe" not found situation but my understanding is that is a Window / Visual Studio problem, not yours.  I'm in the process of uninstalling VS2015 and moving back to VS2019.

**Comment by egraether** [comment]
Those 3 lines are easily fixed with #986. But I'm surprised those are the only lines with this issue. This is also not an issue in our Visual Studio and Appveyor builds. On the other hand, this particular piece of code is still rather new.

**Comment by PhilG57** [comment]
Hi.  Made this change to comment out the old code and replace with the suggested code.  I'm not comfortable enough with C++ to figure out either what I've done wrong, or how to correct the code.

void CodeFocusHandler::setFocusedLocationId(
	QtCodeArea* area, size_t lineNumber, size_t columnNumber, Id locationId, const std::vector<Id>& tokenIds, bool updateTargetColumn, bool fromMouse)
{
	if (updateTargetColumn)
	{
		m_targetColumn = columnNumber;
	}

//PhilG	setCurrentFocus({nullptr, area, nullptr, lineNumber, columnNumber, locationId, tokenIds}, fromMouse);
//PhilG	setCurrentFocus({}, fromMouse);
	setCurrentFocus({nullptr, area, nullptr, lineNumber, columnNumber, locationId, tokenIds}, fromMouse);
	const Focus focus {nullptr, area, nullptr, lineNumber, columnNumber, locationId, tokenIds};
	setCurrentFocus(focus, fromMouse);
}
===================================================

This is what VS 2019 has to say---

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "memory"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\Message.h	4	
Error (active)	E1696	cannot open source file "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\Message.h	5	
Error (active)	E1696	cannot open source file "ostream"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageBase.h	4	
Error (active)	E1696	cannot open source file "sstream"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageBase.h	5	
Error (active)	E1696	cannot open source file "deque"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageQueue.h	4	
Error (active)	E1696	cannot open source file "memory"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageQueue.h	5	
Error (active)	E1696	cannot open source file "mutex"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageQueue.h	6	
Error (active)	E1696	cannot open source file "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageQueue.h	7	
Error (active)	E1696	cannot open source file "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\type\focus\MessageFocusIn.h	4	
Error (active)	E1696	cannot open source file "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\type\focus\MessageFocusOut.h	4	
Error (active)	E1696	cannot open source file "cstddef"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\types.h	4	
Error (active)	E1696	cannot open source file "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.h	4	
Error (active)	E1696	cannot open source file "algorithm"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	4	
Error (active)	E1696	cannot open source file "deque"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	5	
Error (active)	E1696	cannot open source file "sstream"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	6	
Error (active)	E1696	cannot open source file "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	7	
Error (active)	E1696	cannot open source file "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	8	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageBase.h	27	
Error (active)	E0135	namespace "std" has no member "wostream"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageBase.h	105	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib\utility\messaging\MessageBase.h	107	
Error (active)	E0135	class "CodeFocusHandler::Focus" has no member "tokenIds"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	47	
Error (active)	E0135	class "CodeFocusHandler::Focus" has no member "tokenIds"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	47	
Error (active)	E0135	class "CodeFocusHandler::Focus" has no member "tokenIds"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	48	
Error (active)	E0135	class "CodeFocusHandler::Focus" has no member "tokenIds"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	50	
Error (active)	E0135	class "CodeFocusHandler::Focus" has no member "tokenIds"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	56	
Error (active)	E0135	class "CodeFocusHandler::Focus" has no member "tokenIds"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	58	
Error (active)	E0260	explicit type is missing ('int' assumed)	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	85	
Error (active)	E0018	expected a ')'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	85	
Error (active)	E0020	identifier "updateTargetColumn" is undefined	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	87	
Error (active)	E0020	identifier "tokenIds" is undefined	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	94	
Error (active)	E0020	identifier "fromMouse" is undefined	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	94	
Error (active)	E0077	this declaration has no storage class or type specifier	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.h	31	
Error (active)	E0135	namespace "std" has no member "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.h	31	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.h	31	
Error (active)	E0260	explicit type is missing ('int' assumed)	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.h	55	
Error (active)	E0018	expected a ')'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.h	55	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	12	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	12	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	13	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	13	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	16	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	16	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	19	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	19	
Error (active)	E0135	namespace "std" has no member "deque"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	21	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	21	
Error (active)	E0135	namespace "std" has no member "deque"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	22	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	22	
Error (active)	E0135	namespace "std" has no member "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	23	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	23	
Error (active)	E0135	namespace "std" has no member "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	24	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	24	
Error (active)	E0135	namespace "std" has no member "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	25	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	25	
Error (active)	E0135	namespace "std" has no member "vector"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	26	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	26	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	29	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	29	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	32	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	32	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	34	
Error (active)	E0260	explicit type is missing ('int' assumed)	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	34	
Error (active)	E0018	expected a ')'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	34	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	35	
Error (active)	E0260	explicit type is missing ('int' assumed)	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	35	
Error (active)	E0018	expected a ')'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	35	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	36	
Error (active)	E0260	explicit type is missing ('int' assumed)	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	36	
Error (active)	E0018	expected a ')'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	36	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	37	
Error (active)	E0260	explicit type is missing ('int' assumed)	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	37	
Error (active)	E0018	expected a ')'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	37	
Error (active)	E0135	namespace "std" has no member "deque"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	39	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	39	
Error (active)	E0135	namespace "std" has no member "deque"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	40	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	40	
Error (active)	E0135	namespace "std" has no member "deque"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	41	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	41	
Error (active)	E0135	namespace "std" has no member "deque"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	42	
Error (active)	E0065	expected a ';'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	42	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	44	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	44	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	45	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	45	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	45	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	46	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	46	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	47	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	47	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	48	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	48	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	49	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	49	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	50	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	50	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	50	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	62	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	62	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	63	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	63	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	64	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	64	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	65	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	65	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	68	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	68	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	70	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	70	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	70	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	70	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	71	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	71	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	71	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	71	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	73	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	74	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	74	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	75	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	76	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	76	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	78	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	78	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	79	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	79	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	80	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	81	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	82	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	83	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	87	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	87	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	88	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	88	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	97	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	97	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	98	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	98	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	100	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	100	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	102	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	102	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	105	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	105	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	122	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	122	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	139	
Error (active)	E0135	namespace "std" has no member "string"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	139	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	158	
Error (active)	E0135	namespace "std" has no member "wstring"	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_utility\utility\utilityString.h	158	
Error	C2664	'void CodeFocusHandler::setCurrentFocus(const CodeFocusHandler::Focus &,bool)': cannot convert argument 1 from 'initializer list' to 'const CodeFocusHandler::Focus &'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	94	
Error	C2440	'initializing': cannot convert from 'initializer list' to 'CodeFocusHandler::Focus'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	95

**Comment by mlangkabel** [comment]
Looks like your compiler does not find the standard library on your machine.

**Comment by PhilG57** [comment]
Well, hopefully corrected screwed up VS install; now back on VS 2017 and most files compile cleanly. However I still have problem with CodeFocusHandler.cpp:

void CodeFocusHandler::setFocusedScopeLine(QtCodeArea* area, QPushButton* scopeLine, size_t lineNumber)
{
//PhilG	setCurrentFocus({nullptr, area, scopeLine, lineNumber, 0, 0, {}}, false);
	const Focus focus {nullptr, area, scopeLine, lineNumber, 0, 0, {}};
	setCurrentFocus({}, false);
}

Lines 92, 95, and 109 still get this:
  Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'initializing': cannot convert from 'initializer list' to 'CodeFocusHandler::Focus'	Sourcetrail_lib_gui	C:\Sourcetrail-2020.1.117\src\lib_gui\qt\element\code\CodeFocusHandler.cpp	95	

LMK, but no hurry as this is a part time effort for me.

**Comment by egraether** [comment]
I think your C++ setup is broken. I am no expert, but if you have issues with your standard library, this might also cause [std::initializer_list](https://en.cppreference.com/w/cpp/utility/initializer_list) to be missing, which I think is required in this case.
